---
- name: "Installing vagrant {{Project_Version}}"
  package: name={{ item }} state=installed
  with_items:
    - vagrant

- name: copy ssh-keys in setup directory {{ Vagrant_Setup_Version }}
  copy: src=roles/vagrant/files/ssh-keys dest={{Vagrant_Setup_Path}} directory_mode=yes

- name: copy Vagrantfile of kalilinux in setup directory {{ Vagrant_Setup_Version }}
  template: src=roles/vagrant/templates/Vagrantfile-kali.j2 dest={{Vagrant_Setup_Path}}/Vagrantfile
