---
- name: "Installing vagrant {{Project_Version}}"
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - vagrant

- name: copy ziya script in /usr/bin
  copy:
    src: ziya
    dest: /usr/bin/ziya
    mode: 0755

- name: create kali2017-2 directory
  file:
    path: "{{ path_kali2017 }}"
    state: directory

- name: copy ssh-keys in path_kali2017 directory
  copy:
    src: ssh-keys
    dest: "{{ path_kali2017 }}"
    directory_mode: yes

- name: copy Vagrantfile of kalilinux in path_kali2017 directory
  template:
    src: Vagrantfile-kali.j2
    dest: "{{ path_kali2017 }}/Vagrantfile"
